### ISSUE TITLE
Hap.py installation error

### ISSUE THREAD

**Issue by pinninti19** [Illumina/hap.py#39]
Hi, not able to install hap.py

    git clone https://github.com/sequencing/hap.py
    mkdir hap.py-build
    cd hap.py-build
    Run CMake
    cmake ../hap.py
    Build
    make
After make it showing error, can any one help me with installation ?

jsoncpp.cpp:(.text._ZN4Json6Reader15StructuredErrorC2EOS1_[_ZN4Json6Reader15StructuredErrorC5EOS1_]+0x45): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/c++/main/CMakeFiles/xcmp.dir/build.make:111: bin/xcmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:304: src/c++/main/CMakeFiles/xcmp.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

**Comment by pkrusche** [comment]
Hi, could you perhaps post some details on your system + compiler versions?

Do you have an installation of libstdc++-dev? It seems that it is trying to link only with a C compiler, or that there is no C++ STL library installed.

**Comment by pinninti19** [comment]
Firstly, thanks for reply. I had GCC already installed.
Find the attached.

Best,

**Comment by pkrusche** [comment]
Hi, I think your email attachment didn't get picked up by github -- could you please try to upload it on the Github issue directly?

Depending on your system / distribution, you will need to have installations of `gcc`, `g++` and `libc++` or `libstdc++` (`-devel` packages s.t. headers are available). GCC needs to be newer than 4.9.x.

**Comment by pinninti19** [comment]
Hi

again error (I installed gcc, g++ and libc ++)
jsoncpp.cpp:(.text._ZN4Json6Reader15StructuredErrorC2EOS1_[_ZN4Json6Reader15StructuredErrorC5EOS1_]+0x45):
undefined reference to `std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char>
>::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> >&&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/c++/main/CMakeFiles/xcmp.dir/build.make:111: bin/xcmp]
Error 1
make[1]: *** [CMakeFiles/Makefile2:304:
src/c++/main/CMakeFiles/xcmp.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

**Comment by pkrusche** [comment]
Which system (Linux distribution / MacOS version?) are you working on? A full list of dependencies for Ubuntu can be found in the Dockerfile here: https://github.com/Illumina/hap.py/blob/master/Dockerfile

**Comment by pinninti19** [comment]
I'm working on ubuntu 16.04LTS

**Comment by pkrusche** [comment]
The Dockerfile should show all the packages you need then -- I think by default Ubuntu may not come with all development tools and libraries needed for hap.py. Could you please check that you have all the following libraries installed:

```
build-essential 
zlib1g-dev
libbz2-dev
pkg-config
cmake
libncurses5-dev
autoconf
git
bzip2 
wget
python2.7
python2.7-dev
python
python-setuptools 
python-pip 
python-psutil 
cython 
python-numpy 
python-pandas 
python-distribute 
python-pysam 
python-scipy 
software-properties-common
python-software-properties
```

**Comment by pkrusche** [comment]
Another issue may be that you need to delete the build folder for Cmake and start from scratch -- Cmake can get confused when additional packages / compilers appear between builds.

**Comment by pinninti19** [comment]
Hi Peter
I installed, using docker. The hap.py only only runs with a reference hg19
?

**Comment by pkrusche** [comment]
You can specify a different reference fasta using the `-r` command line switch. Note that the reference fasta must be the same for all input files (truth, query, any bed file).

**Comment by pinninti19** [comment]
Its showing error, confidence and bed file downloaded from ncbi-ftp site.

bed file - HG005_GRCh38
confidence vcf - HG005_GRCh38 (Chinese son)
qury vcf - exome vcf (1000 g dataset)

root@f81419609198:/opt/hap.py/bin# ./hap.py
/home/likithreddy/Documents/Genome/confidencecalls/Latestconfidencecalls/ChineseSon/HG005_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC-SOLIDgatkHC_CHROM1-22_v.3.3.2_highconf.vcf
/home/likithreddy/Documents/Genome/vcf/SRR098401.Aligner.freebayes.raw.SNV.vcf
-f
/home/likithreddy/Documents/Genome/confidencecalls/Latestconfidencecalls/ChineseSon/HG005_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC-SOLIDgatkHC_CHROM1-22_v.3.3.2_highconf.bed
-o outputson -r /home/likithreddy/Documents/Genome/hg38.fa
2018-02-07 15:23:32,691 WARNING  No reference file found at default
locations. You can set the environment variable 'HGREF' or 'HG19' to point
to a suitable Fasta file.
2018-02-07 15:23:32,692 WARNING  No reference file found at default
locations. You can set the environment variable 'HGREF' or 'HG19' to point
to a suitable Fasta file.
2018-02-07 15:23:32,796 ERROR    FP/confident call region bed file does not
exist.
2018-02-07 15:23:32,797 ERROR    Traceback (most recent call last):
2018-02-07 15:23:32,797 ERROR      File "./hap.py", line 508, in <module>
2018-02-07 15:23:32,797 ERROR        main()
2018-02-07 15:23:32,797 ERROR      File "./hap.py", line 198, in main
2018-02-07 15:23:32,797 ERROR        raise Exception("FP/confident call
region bed file does not exist.")
2018-02-07 15:23:32,797 ERROR    Exception: FP/confident call region bed
file does not exist.

Thanks

**Comment by pkrusche** [comment]
The reference file is not the problem (the reference-related messages are just warnings), it seems the confident region file path does not exist. Have you mounted your home folder inside Docker using `-v`, and does the file exist?

**Comment by pinninti19** [comment]
I don't have any idea, how to mount docker ?

**Comment by pkrusche** [comment]
When you run docker, run it with `-v /home/likithreddy:/home/likithreddy` -- this will make your home directory available inside Docker. See here: https://stackoverflow.com/questions/23439126/how-to-mount-host-directory-in-docker-container

**Comment by pinninti19** [comment]
Thanks! hap.py working.

**Comment by pkrusche** [comment]
Great, happy to hear!

**Comment by pinninti19** [comment]
Hi

I run the hap.py for my vcf. I can understand the output table. I wish to
do roc plot (Precision vs sensitivity) so, which file should i give as
input ?
I had 4 vcf from one dataset with different variant calling process.
Thanks!

**Comment by pinninti19** [comment]
Could you please tell me the difference between the hap.py and RTG tool.
Both of them do the same job isn't ?

**Comment by pkrusche** [comment]
To create plots + analysis, we have published a separate R package here: https://github.com/illumina/happyR -- this has some documentation also. Also, the GA4GH benchmarking toolset contains scripts for interactive reporting based on hap.py results: https://github.com/ga4gh/benchmarking-tools/tree/master/reporting/basic 

RTG vcfeval can be used inside hap.py to compare variants. It will become the default option in the next version. The main added value of hap.py is that it provides preprocessing, stratification and a more detailed breakdown of metrics. Also, hap.py facilitates running comparisons that follow the GA4GH best-practices for variant benchmarking.
